version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_URL=http://localhost:8080
      - DB_HOST=postgres
      - DB_NAME=maxit_db
      - DB_USERNAME=maxit_user
      - DB_PASSWORD=maxit_password
      - DSN=pgsql:host=postgres;port=5432;dbname=maxit_db
    depends_on:
      - postgres
    volumes:
      - ./public/uploads:/var/www/html/public/uploads

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: maxit_db
      POSTGRES_USER: maxit_user
      POSTGRES_PASSWORD: maxit_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/script.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
